name: "Code scanning - action"

on: [push]

jobs:
  Run:
    strategy:
      fail-fast: false
    runs:
      using: 'docker'
      image: 'Dockerfile'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Rubocop run
      uses: ./ # Uses an action in the root directory

        

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
