name: "Code scanning - action"

on: [push]

jobs:
  rubocop_job:
    runs-on: ubuntu-latest
    name: Job to run rubocop and save results
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Rubocop run
      uses: ./ # Uses an action in the root directory

        

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
