name: "Rubocop"

on: [push]

jobs:
  rubocop_job:
    runs-on: ubuntu-latest
    name: Code Scanning Rubocop integration
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Rubocop scan
      uses: arthurnn/code-scanning-rubocop/rubocop-scan@master

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: rubocop.sarif
