name: "Code scanning - action"

on: [push]

jobs:
  Run:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Rubocop run
      run: |
        mkdir ../results
        echo $(pwd)
        gem install rubocop

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
