name: "Code scanning - action"

on: [push]

jobs:
  Code-Scanning-Build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
